---
title: "Evaluate elections"
date: '`r Sys.Date()`'
output: 
  pdf_document: 
    toc: yes
    number_sections: yes
    toc_depth: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(adapop)
paths_to_pop_objects <- "[pop_paths]"
pops <- adapop:::rmd_read_pops(paths_to_pop_objects)

parameter_path <- "[parameter_path]"
param_default <- c("full_period" = FALSE, 
                   "last_election_period" = TRUE,
                   "election_periods" = FALSE,
                   "election_campaigns" = FALSE,
                   "diagnostics_table" = TRUE,
                   "model_information" = TRUE,
                   "traceplots" = FALSE,
                   "dev" = "png")
params <- adapop:::rmd_read_params(parameter_path)
params <- adapop:::rmd_parse_parameters(params, param_default)

parties <- adapop:::rmd_pops_unique_parties(pops)

mi <- adapop:::rmd_model_settings_with_unique(pops)
mi <- mi[order(mi$y, mi$polls_time_to, mi$model_setting),]
mi$model <- mi$i

mu <- adapop:::rmd_model_settings_unique(pops)

knitr::opts_chunk$set(dev = params$dev)
```

\pagebreak

# Industry bias

```{r,results='asis', echo=FALSE}

if(params$model_information){
  cat("\n## Model settings\n")
  knitr::kable(mu, 
              caption = "Model settings", 
              row.names = FALSE)
}
```


```{r, echo=FALSE, results='asis', fig.height=3, fig.width=4, fig.align="center", out.width="50%"}
if(params$last_election_period){
  cat("## Kappa estimates by party\n")
  for(i in seq_along(parties)){
    party <- parties[i]
    cat("\n### ", party, "\n")
    for(j in 1:nrow(mi)){
      cat("\n")
      pop <- pops[[mi$i[j]]]
      knm <- adapop:::rmd_get_kappa_name(pop)
      if(!(party %in% pop$y)) next
      no_kappa <- pop$stan_fit@par_dims[[knm]][1]
      date_idx <- (length(pop$known_state$date) - no_kappa + 2L):length(pop$known_state$date)
      kidx <- which(pop$y %in% party)
      tit <- paste0("Kappa (", parties[i], ", ", mi$model_setting[j],", model: ",mi$i[j],", ",substr(mi$sha[j], 1,6),")")
      plt <- plot_parameters_areas(pop, 
                                   paste0(knm, "[", 1:no_kappa, ",", kidx, "]"),
                                   c(substr(pop$known_state$date[date_idx],1,4), "next"), 
                                   title = tit)
      suppressWarnings(print(plt))
      cat("\n")
    }
    cat("\n")
  }
}
```

```{r, echo=FALSE, results='asis', fig.width=6}
if(params$traceplots){
  cat("## Kappa[next]: traceplots and Rhat\n")
  for(j in 1:nrow(mi)){
      cat("\n")
      pop <- pops[[mi$i[j]]]
      knm <- adapop:::rmd_get_kappa_name(pop)
      parties <- pop$y
      no_kappa <- pop$stan_fit@par_dims[[knm]][1]
      param <- paste0(knm, "[", no_kappa, ",", seq_along(pop$y), "]")
      
      tab <- data.frame(parameter = param, y = pop$y, pop$diagnostics$Rhat[param])
      
      plt <- traceplot(pop, param,
                       ncol = 2)
      tit <- paste0("Kappa traceplot (", mi$model_setting[j],", model: ",mi$i[j],", ",substr(mi$sha[j], 1,6),")")
      print(knitr::kable(tab, 
             digits = 2, 
             caption = tit, 
             row.names = FALSE))
      cat("\n")
      print(plt)
      cat("\n")

  }
}

```


```{r, echo=FALSE, results='asis', fig.height=3, fig.width=4, fig.align="center", out.width="50%"}
if(params$last_election_period){
  cat("## sigma_kappa\n")
  for(j in 1:nrow(mi)){
      cat("\n")
      pop <- pops[[mi$i[j]]]
      no_sigma_kappa <- pop$stan_fit@par_dims$sigma_kappa
      sigma_kappa_names <- pop$y
      if(no_sigma_kappa == 1L) sigma_kappa_names <- "sigma_kappa"
      tit <- paste0("sigma_kappa (Setting: ", mi$model_setting[j],", mod: ",mi$i[j],", ",substr(mi$sha[j], 1,6),")")
      plt <- plot_parameters_areas(pop, 
                                   paste0("sigma_kappa[", 1:no_sigma_kappa, "]"), 
                                   pop$y, 
                                   title = tit) 
      suppressWarnings(print(plt))
      cat("\n")
  }
}

```

```{r, echo=FALSE, results='asis', fig.width=6}
if(params$traceplots){
  cat("## sigma_kappa: traceplots and Rhat\n")
  for(j in 1:nrow(mi)){
      cat("\n")
      pop <- pops[[mi$i[j]]]
      knm <- adapop:::rmd_get_kappa_name(pop)
      parties <- pop$y
      no_kappa <- pop$stan_fit@par_dims[[knm]][1]
      param <- paste0("sigma_kappa[", seq_along(pop$y), "]")
      
      tab <- data.frame(parameter = param, y = pop$y, Rhat =pop$diagnostics$Rhat[param])
      
      plt <- traceplot(pop, param,
                       ncol = 2)
      tit <- paste0("Sigma_kappa traceplots (", mi$model_setting[j],", model: ",mi$i[j],", ",substr(mi$sha[j], 1,6),")")
      print(knitr::kable(tab, 
             digits = 2, 
             caption = tit, 
             row.names = FALSE))
      cat("\n")
      print(plt)
      cat("\n")
  }
}

```

```{r, echo=FALSE, results='asis', fig.height=3, fig.width=4, fig.align="center", out.width="50%"}
if(params$last_election_period){
  cat("## alpha_kappa \n")
  for(j in 1:nrow(mi)){
      cat("\n")
      pop <- pops[[mi$i[j]]]
      alpha <- pop$stan_data$stan_data$estimate_alpha_kappa
      if(is.null(alpha) || alpha < 1) next
      tit <- paste0("alpha_kappa (Setting: ", mi$model_setting[j],", mod: ",mi$i[j],", ",substr(mi$sha[j], 1,6),")")
      plt <- plot_parameters_areas(pop, 
                                   paste0("alpha_kappa[1]"), 
                                   "alpha_kappa", 
                                   title = tit) 
      suppressWarnings(print(plt))
      cat("\n")
  }
}

```


```{r, echo=FALSE, results='asis', fig.height=3, fig.width=4, fig.align="center", out.width="50%"}
if(params$last_election_period){
  cat("## nu_kappa \n")
  for(j in 1:nrow(mi)){
      cat("\n")
      pop <- pops[[mi$i[j]]]
      use_t <- pop$stan_data$stan_data$use_t_dist_industry_bias
      if(is.null(use_t) || use_t < 1) next
      tit <- paste0("nu_kappa (Setting: ", mi$model_setting[j],", mod: ",mi$i[j],", ",substr(mi$sha[j], 1,6),")")
      plt <- plot_parameters_areas(pop, 
                                   paste0("nu_kappa[1]"), 
                                   "nu_kappa", 
                                   title = tit)
      suppressWarnings(print(plt))
      cat("\n")
  }
}

```


\pagebreak



# Model information

```{r, results='asis', echo=FALSE}
if(params$diagnostics_table){
  
  cat("## Model diagnostics\n")
  tab <- adapop:::rmd_model_diagnostic_table(pops)
  n <- 5
  it <- ncol(tab)%/%n; rest <- ncol(tab)%%n
  if(rest > 0) it <- it + 1L
  for(i in 1:it){
    if(i == it) end <- ncol(tab) else end <- i*n
    ptab <- tab[,((i-1)*n + 1L):end, drop=FALSE]
    print(knitr::kable(ptab, 
                 digits = 1, 
                 caption = paste0("Model diagnostics ", i), 
                 row.names = TRUE))
  }

}
```


```{r,results='asis', echo=FALSE}

if(params$model_information){

  cat("\n## Model summary\n")
  knitr::kable(mi[order(mi$model), c("model", "sha", "model_setting", "polls_time_to")], 
               digits = 1, 
               caption = "Model summary", 
               row.names = FALSE)
  
}
```


```{r,results='asis', echo=FALSE}
if(params$model_information){
  rmd_print_model_information(pops)
}
```
