# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    paths:
      - 'rpackage/**'
    branches:
      - main
      - test
      - dev
      - master
  pull_request:
    branches:
      - main
      - test
      - dev
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: r-${{ hashFiles('DESCRIPTION') }} # key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('DESCRIPTION') }}
      - name: Install libcurl
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Install dependencies
        run: |
          Sys.getenv("GITHUB_REF")
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(pkgdir = "rpackage", dependencies = TRUE)
        shell: Rscript {0}
      - name: Install SwedishPolls
        run: |
          remotes::install_github("MansMeg/SwedishPolls", subdir = "RPackage")
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(path = "rpackage", args = "--no-manual", error_on = "warning")
        shell: Rscript {0}
